### ISSUE TITLE
Guild Wars management.

### ISSUE THREAD

**Issue by westwol** [otsoft/myaac#13]
I've tried to adapt Gesior's script but could not make it work.

**Comment by slawkens** [comment]
I will make Guild Wars management page in upcoming versions.

**Comment by slawkens** [comment]
Update: This has my highest priority, so I'm working on this in my spare time.

But: the problem is, there is much more to do. Not just guild wars, but the whole guilds page need to be rewritten, cause it seems to look different in the newest tibia.

**Comment by YohanAugusto** [comment]
Do you still need help?

**Comment by RajasEdge** [comment]
I'm already looking for errors and looking at model to be able to implement.

**Comment by augustorajas** [comment]
Up!

**Comment by tyndy125** [comment]
Nothing new ??

**Comment by augustorajas** [comment]
UP!

**Comment by augustorajas** [comment]
Nothing new ?? Please!!

**Comment by Fiimpz** [comment]
Anything new on this?

**Comment by Leesneaks** [comment]
![image](https://user-images.githubusercontent.com/42119604/106659172-4316ce80-6596-11eb-9c4f-dd66c963e7b5.png)
Still away off yet but i'm working on a default bootstrap theme and will include guild wars as a plugin once complete.

**Comment by augustorajas** [comment]
@slawkens , @Leesneaks Any plans to be implemented?

**Comment by Leesneaks** [comment]
As mentioned previously Its a work in progress, but I have other projects on the go at the moment. It'll happen when it happens.
If anyone else wants to release one they are more than welcome.

**Comment by Chris98N** [comment]
Something new?

**Comment by augustorajas** [comment]
Please, continue!!

**Comment by slawkens** [comment]
Hey,

Guild wars is already done and available as a plugin

https://github.com/otsoft/myaac-plugins/tree/master/guild-wars

However it work only with latest myaac - develop branch, which hasn't been released yet.

**Comment by realebra74** [comment]
> Hey,
> 
> Guild wars is already done and available as a plugin
> 
> https://github.com/otsoft/myaac-plugins/tree/master/guild-wars
> 
> However it work only with latest myaac - develop branch, which hasn't been released yet.

using v8.0.13
Cannot find plugin info .json file. Installation is discontinued.
