### ISSUE TITLE
Support for OTHire

### ISSUE THREAD

**Issue by 5qemeister** [otsoft/myaac#136]
Hey slawkens.

I have question.
Can you add OTHire support?
https://github.com/TwistedScorpio/OTHire/
Idk why but I have some problems when installing, so I think that the myaac doesnt support this one.
Can you take a look on it? :) Very thanks.

Pozdrawiam mordeczko heh 👯

**Comment by slawkens** [comment]
Hey,

What kind of errors do you get?

As far as I know, MyAAC should support OTHire out of the box.

I've added the support in 0.0.3 version IIRC.

**Comment by 5qemeister** [comment]
After update MyAAC, everything is fine. 
I have a question, where can I fix this?
![image](https://user-images.githubusercontent.com/38042309/91086561-5fa9f480-e64f-11ea-9a66-8568160f5dad.png)

OTHire instead of ..getSize have ..getTiles

Thanks for support anyway!

**Comment by slawkens** [comment]
Fixed in: https://github.com/otsoft/myaac/commit/9a475f2c574192918e7b3f10ccb43db64daa0486
