### ISSUE TITLE
Change login form

### ISSUE THREAD

**Issue by RDaruish** [otsoft/myaac#153]
Hello, would there be any way to change the login form of the site to email? if so how can i do it!

**Comment by slawkens** [comment]
Expect it in upcoming days.

I am working on this.

**Comment by tarantonio** [comment]
Any updates?

**Comment by slawkens** [comment]
Hello,

this feature has been implemented in this pull request: https://github.com/slawkens/myaac/pull/159

It's waiting for the approval, then it will be merged into develop branch.

**Comment by tarantonio** [comment]
> Hello,
> 
> this feature has been implemented in this pull request: #159
> 
> It's waiting for the approval, then it will be merged into develop branch.

It's possible to generate a free/valid account number on register form?
That way players don't need to try/retry to get an available number.

**Comment by slawkens** [comment]
I'm cleaning a bit the issues.

As so - I'm going to close this one.

The progress of login by email can be tracked here: https://github.com/otsoft/myaac/pull/159
