### ISSUE TITLE
Bug System Shop

### ISSUE THREAD

**Issue by Hiquezerah** [otsoft/myaac#168]
Utilizo: otx2, versão client: 860
Hi, I'm using the semantic template and installed the shop plugin. And it is not being activated. I already put in config.php "true" and it didn't work.

http://i.prntscr.com/V72lXLQ8RaK2W6JcCZ-l3w.png >> the shop is not active.
http://i.prntscr.com/hKCAdVywRYinTlV3P129Sg.png >> in admin painel

**Comment by slawkens** [comment]
Cannot reproduce in the latest version.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/16687302/172023441-47002ae4-fc64-4a62-9a35-f6f391163519.png">

Did you try the latest - v2.0 version of the semantic-template plugin?

**Comment by slawkens** [comment]
Any update?

**Comment by Hiquezerah** [comment]
hello bro, thanks for all your support!
I ended up choosing another template to work over. I'm not using semantic anymore!
I'm using telara now.
and sorry for the delay!
