### ISSUE TITLE
Found phishing on account management page

### ISSUE THREAD

**Issue by worthdavi** [otsoft/myaac#170]
The account management page is being reported for phishing. YouTube and other domain companies are blocking some websites that use MyAAC.

"*****.com has been suspended due to its blacklisting by Netcraft for phishing activities. Listed below is the URL where the phishing content was found to be hosted.
https://******.com/?subtopic=accountmanagement"

Even the YouTube is blocking any ADs related to the website.

**Comment by slawkens** [comment]
I don't see anything that could cause that except link to download page but that would be malware but not phishing.

Maybe someone else could find the cause.

**Comment by worthdavi** [comment]
Try this one:
https://easyglobalserver.com/

It's using 100% myaac code

**Comment by Leesneaks** [comment]
![image](https://user-images.githubusercontent.com/42119604/129773657-308b2dea-d6e5-4758-984b-a8a7659be409.png)

**Comment by Leesneaks** [comment]
I am closing this as the errors show the website domain as deceptive and not myaac account management.
