### ISSUE TITLE
IPv6 issue when env is set to dev

### ISSUE THREAD

**Issue by Dzanar** [otsoft/myaac#171]
### Server configuration
- Operating System: Ubuntu 20.04 LTS
- Web Server (+ version): nginx/1.21.3
- PHP Version: 8.0.10
- Server name and version (for example: TFS 0.3): TFS 1.3
- MyAAC Version: 0.86

### Client configuration (Your Computer)

- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 Edg/93.0.961.52
- Operating System: Windows 10 Home 21H1

### Steps To Reproduce:
1. Set $config['env'] = 'dev' in config.local.php.
2. When you using IPv6 the page was not load and throw exception

`Whoops something went wrong...
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip' at row 1

Backtrace:

#0 /home/otsmanager/www/nelena/system/libs/visitors.php(97): PDO->exec()
#1 /home/otsmanager/www/nelena/system/libs/visitors.php(40): Visitors->addVisitor()
#2 /home/otsmanager/www/nelena/index.php(240): Visitors->__construct()
#3 {main}`

**Comment by slawkens** [comment]
Thanks for reporting this.

The solution is to resize the ip field in visitors table.

The query:
```
ALTER TABLE `myaac_visitors` MODIFY `ip` VARCHAR(45) NOT NULL;
```
