### ISSUE TITLE
`premdays` -> `premium_ends_at` for compatibility with latest TFS

### ISSUE THREAD

**Issue by EPuncker** [otsoft/myaac#179]
### Server configuration
- Server name and version (for example: TFS 0.3): latest tfs 1.4 master
- MyAAC Version: latest

### Description:
Since 28th october 2020, tfs-master have changed `premdays` table to `premium_ends_at`

A person have reported it in the forum [here](https://otland.net/threads/error-in-console-regarding-login.278588/), so I opened an issue here just in case, I believe after protocol 12 more people will start using tfs master and this will be a needed change.

Here is how ZnoteAAC handled it, might be useful: https://github.com/Znote/ZnoteAAC/commit/fa5fac75a78437605a71c34851c7b8fbc1a4a2ae

**Comment by Leesneaks** [comment]
Hey EPuncker,
Thanks for submitting this.
https://github.com/slawkens/myaac/blob/master/system/libs/pot/OTS_Account.php#L190

[0.8.4 - 18.02.2021]
Added
support for accounts.premium_ends_at (Latest TFS 1.x)

I  have asked user for more information on the otland forum post as I would say its server related from what he posted.

**Comment by slawkens** [comment]
As said, this is already implemented. 

Everyone is able to test and see if it works :)
