### ISSUE TITLE
Highscores showing only 34 characters

### ISSUE THREAD

**Issue by Risk-CPU** [otsoft/myaac#181]
### Server configuration
- Operating System:  linux
- Web Server (+ version): 
- PHP Version: 
- Server name and version (for example: TFS 0.3):  1.3
- MyAAC Version: latest

### Client configuration (Your Computer)

- Browser: 
- Operating System: ubuntu

### Description:
highscores doesnt show more than 34 characters, not really sure where the problem is there.

### Steps To Reproduce:

**Comment by slawkens** [comment]
And how many characters do you have in database?

**Comment by slawkens** [comment]
Any update? Otherwise I will need to close this as not enough information are provided.
