### ISSUE TITLE
Admin Panel - Gifts

### ISSUE THREAD

**Issue by tvrfps** [otsoft/myaac#182]
The admin/pages/gifts.php path is wrong on Plugin File. The actual plugin file is "system/pages/admin/gifts.php" and If you just install it by Admin Panel, when you try to edit by panel you see "404 Not Found - The Requested URL /admin/?p=gifts was not found on this server. But if you manually copy the gifts.php file and paste on Admin/Pages the admin gifts will works.

Just change the Gesior Shop Plugin the folder _system/pages/admin/gifts.php_ for **admin/pages/gifts.php**

**Comment by slawkens** [comment]
Thanks for reporting.

A bit late, but I just updated the plugin with the correct file path.

For all the are interested, the latest version of the plugin can be downloaded here:
https://my-aac.org/plugins/
