### ISSUE TITLE
Client 12 issue with login plugin

### ISSUE THREAD

**Issue by Rockerszzz** [otsoft/myaac#183]
### Server configuration
- Operating System: Ubuntu 20.04 LTS
- Web Server (+ version): php 7.4
- PHP Version: 7.4
- Server name and version (for example: TFS 0.3): TFS 1.4
- MyAAC Version: 0.8.6

### Client configuration (Your Computer)

- Browser: Chrome
- Operating System: Windows
- Tibia Client: 12.70

### Steps To Reproduce: When using myaac in version 0.8.6 with the login plugin for client 12 in version 2.0 and trying to log in to the tibia client it returns the following error: "Lofin failed. Tibia might currently be down for maintenance. Please try again later ."

**Comment by RCP91** [comment]
Mine only entered using otclient in version 1099
Server creating in the cloud.
