### ISSUE TITLE
[Suggestion] Reward for users that confirm their e-mail

### ISSUE THREAD

**Issue by EPuncker** [otsoft/myaac#184]
We all know lots of players just create accounts with non existing email just to "try out" the server, so what about a feature that would actually reward users with premium points/days if they actually confirm their email?

**Comment by slawkens** [comment]
![image](https://user-images.githubusercontent.com/16687302/216615010-f1d2bad2-7c2c-4c1e-9ad4-74e293b18d8a.png)

Hello, thanks for this clever idea.

Soo, I would like to inform you that I did this :)

The whole code is available in this commit, and is included into master branch (MyAAC 0.8.x), without need for installing a separate plugin.

https://github.com/otsoft/myaac/commit/43c197316ae7077b44a475e2429c1a0174e407c9
