### ISSUE TITLE
New character skill is different than Sample players

### ISSUE THREAD

**Issue by lucasgrizante** [otsoft/myaac#187]
New character skills aren't copied from Sample characters

**Comment by Leesneaks** [comment]
https://github.com/otsoft/myaac/blob/master/system/libs/CreateCharacter.php#L155

`$player->setSkill($skill, $char_to_copy->getSkill($skill));`

https://github.com/otsoft/myaac/blob/master/system/libs/CreateCharacter.php#L197

`$db->query('INSERT INTO `player_skills` (`player_id`, `skillid`, `value`, `count`) VALUES ('.$player->getId().', '.$i.',  $char_to_copy->getSkill($i), 0)');`


slaw
Maybe something like that? Untested.

**Comment by Leesneaks** [comment]
Just noticed the pull request.. lol. ma bad.
