### ISSUE TITLE
bug when trying to create 2 characters with the same name

### ISSUE THREAD

**Issue by Hiquezerah** [otsoft/myaac#191]
I am using
Myaac version lastet 0.8.6
Ubuntu 20.04
OTXServer 2 / 2.15
Client Custom : 8.60
Database OTX

Hello, how is everything?
I was creating my samples here and discovering a bug.

When creating a character and if I try to create a character with the same name without then the error happens!
Example: Create a character with the name "myacc", after the character is created and try to create another character with the same name "myacc" the error happens, you know?
![image](https://user-images.githubusercontent.com/88052650/160272320-1cf3f01d-ff3c-4773-8d51-598714c023a6.png)

note: I don't want you to be able to create characters with the same name, I just wanted to solve this error!

**Comment by slawkens** [comment]
But you are logged in as an admin account, do you?

**Comment by Hiquezerah** [comment]
sorry bro, really I was on an admin account redoing the samples and didn't notice. I just tested with a normal account and it returned correctly. 

**The Following Errors Have Occurred:
Character with this name already exist.**
Sorry bro

**Comment by slawkens** [comment]
No problem ;)

Thanks for reporting, because its a bug anyway.
