### ISSUE TITLE
gift.php bug

### ISSUE THREAD

**Issue by Hiquezerah** [otsoft/myaac#193]
Hello, I just tested the gift system on my server and when trying to buy an item in the shop returns this error.
![image](https://user-images.githubusercontent.com/88052650/165042132-85e1d3a2-eaf6-4fff-9519-783ff0cea009.png)
Tested with the character online and offline, both return the same error.
i tested find some solution and did not find, could you help me?
I'm using: Otx 2.15 https://github.com/mattyx14/otxserver/tree/otxserv2
and I'm using this version of shop system:
![image](https://user-images.githubusercontent.com/88052650/165044997-afb061b6-25d8-4c27-baa9-cfad18666ed9.png)
would it be possible to put to buy item in the shop only if the character is online?

**Comment by ivenspontes** [comment]
passing the login column empty, with it being not null it ends up returning this error, try monitor sql queries, but I didn't see in that plug-in column login, try to review your tables

**Comment by slawkens** [comment]
You need to remove z_ots_comunication table in your database, then reimport it from original plugin.

Here's the query to reimport:
```
CREATE TABLE IF NOT EXISTS `z_ots_comunication` (
	`id` INT(11) NOT NULL auto_increment,
	`name` VARCHAR(255) NOT NULL DEFAULT '',
	`type` VARCHAR(255) NOT NULL DEFAULT '',
	`action` VARCHAR(255) NOT NULL DEFAULT '',
	`param1` VARCHAR(255) NOT NULL DEFAULT '',
	`param2` VARCHAR(255) NOT NULL DEFAULT '',
	`param3` VARCHAR(255) NOT NULL DEFAULT '',
	`param4` VARCHAR(255) NOT NULL DEFAULT '',
	`param5` VARCHAR(255) NOT NULL DEFAULT '',
	`param6` VARCHAR(255) NOT NULL DEFAULT '',
	`param7` VARCHAR(255) NOT NULL DEFAULT '',
	`delete_it` INT(2) NOT NULL DEFAULT '1',
	PRIMARY KEY  (`id`)
) ENGINE=MyISAM;
```

That't the bug with your previous table, not in myaac - so I'm closing this.
