### ISSUE TITLE
players not showing on highscore page but showing on topPlayers box

### ISSUE THREAD

**Issue by Juanzin420** [otsoft/myaac#195]
![image](https://user-images.githubusercontent.com/64820180/169629738-0a6ecf33-1254-41ef-b3bd-1b8a7da4e4fa.png)

### Server configuration
- Server name and version (for example: TFS 0.3): Nostalrius 772
- MyAAC Version: most recent

**Comment by antoniovikernes** [comment]
me too im having this trouble

**Comment by slawkens** [comment]
Thanks for report guys.

That's the bug I accidentally added into highscores.php in this commit: https://github.com/otsoft/myaac/commit/9e949eb32a40d426a4cdc848442e8e12bc322f4b

Now the fix is here: https://github.com/otsoft/myaac/commit/3d56214c078871cb98345589b22dfde8eb14ed73
