### ISSUE TITLE
account invalid when try join in client

### ISSUE THREAD

**Issue by oldpowerz** [otsoft/myaac#197]
Hello, I have been having problems with the page when creating an account. I decided to remove the salt and put it in plain to see what was happening and I noticed that when you create an account, the accountname creates it as normal, but the password literally does not place anything. ![image](https://user-images.githubusercontent.com/71293715/172077831-04be1916-c7c3-438d-942c-e780c6eae9c4.png)

i using tfs 0.4

fixed
for those who do not know is to edit the createaccount.php file and delete

$config_salt_enabled = $db->hasColumn('accounts', 'salt');
		if($config_salt_enabled)
		{
			$salt = generateRandomString(10, false, true, true);
			$password = $salt . $password;
		}
		if($config_salt_enabled)
			$new_account->setCustomField('salt', $salt);
			
at least it worked for me

**Comment by WalistonBelles** [comment]
Maybe the site was trying to encrypt your password, but it couldn't and the field was empty. Then he would insert null into the password field in his database. However, as you already solved the problem, I think it would be interesting to close the issue.

**Comment by slawkens** [comment]
You can also just delete "salt" from "accounts" table in database.

Then refresh the cache in admin panel or set "env" to "dev" in config.local.php
