### ISSUE TITLE
Blocking account manager login (1/1)

### ISSUE THREAD

**Issue by QuebradaZN** [otsoft/myaac#203]
Any way to block access from account 1/1 (Account Manager) ?
This way they can change the Account Manager password

**Comment by slawkens** [comment]
If you are using Account Manager, then why do you need website? ;)

Anyway.

First option is to delete Account Manager from database.

Second option is to do small fix in the login page to disallow login from account 1.

In this part of code in system/login.php
```
$config_salt_enabled = $db->hasColumn('accounts', 'salt');
	if($account_logged->isLoaded() && encrypt(($config_salt_enabled ? $account_logged->getCustomField('salt') : '') . $login_password) == $account_logged->getPassword()
		&& (!isset($t) || $t['attempts'] < 5)
```

Just after:
`&& (!isset($t) || $t['attempts'] < 5)`
add new line with:
`&& $login_account != 1`

**Comment by QuebradaZN** [comment]
It worked, that way there are many players who are lazy to use the site and others like to follow server news and updates
