### ISSUE TITLE
crash tfs 1.5 and crash edit player for myaac panel admin

### ISSUE THREAD

**Issue by daniofordon** [otsoft/myaac#217]
tfs 1.5  latest (all commit)

myaac latest (all commit)

after refreshing the myaac page, the tfs server crashes

https://prnt.sc/vWBHDMPYPRXV

page crashes when editing player

https://prnt.sc/PZyu0sHNaVmf

**Comment by slawkens** [comment]
fixed https://github.com/otsoft/myaac/commit/a39600efe21038a6a2c73fca9c630afa2095971c
https://github.com/otsoft/myaac/commit/e552bcfe820fa24672881f7fcbedb63f8906602d

about crash in tfs: i have no clue, I need more details, what you edited in player

**Comment by daniofordon** [comment]
https://prnt.sc/APNSsVRQpK16

I installed clean tfs and current myaac and after launching tfs and refreshing the myaac page, the server crashes. i didn't change anything it's clean tfs and clean myaac

**Comment by daniofordon** [comment]
https://prnt.sc/woPWabkUj8yb

Server crashes when choosing a character

**Comment by daniofordon** [comment]
I noticed that it's not a problem of acc maker, but of the tfs itself

**Comment by daniofordon** [comment]
I found the cause of the server crash. if in config.lua instead of the server's ip, he enters the domain connected to vps debian 11, the server crashes. when i enter the server ip, the server works normally.

**Comment by slawkens** [comment]
Closing, as not related to myaac.
